# Generated by Django 4.0 on 2023-04-23 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranged', models.CharField(max_length=1)),
                ('critic', models.CharField(blank=True, max_length=140, null=True)),
                ('books', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.books')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
