# Generated by Django 4.0 on 2023-04-23 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Films',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='books',
            new_name='film',
        ),
    ]
