# Generated by Django 4.0 on 2023-05-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_review_image_url_films_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='banner_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
