# Generated by Django 4.0 on 2023-05-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_films_banner_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='films',
            name='image_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='critic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
